apiVersion: v1
kind: Service
metadata:
  name: xaiops-ui-service
  labels:
    app: xaiops-ui
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: xaiops-ui
